name: Quality

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: sbt clean test

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck

  compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Did it compile?
        run: sbt compile
